# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rKy1rswu86qT3ubjUv6croFrkO78Kas
"""

# Cell 1 — correct versions that actually exist and are compatible
#!pip uninstall mediapipe protobuf -y -q
!pip install mediapipe==0.10.13

import mediapipe as mp

dir(mp)



import numpy as np
import json
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, LSTM, Dense, Dropout, BatchNormalization,
    Bidirectional, GlobalAveragePooling1D, Multiply,
    Permute, RepeatVector, Flatten, Lambda
)
from tensorflow.keras.callbacks import (
    EarlyStopping, ReduceLROnPlateau,
    ModelCheckpoint, TensorBoard
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
import matplotlib.pyplot as plt

print(f"TensorFlow: {tf.__version__}")
print(f"GPU: {tf.config.list_physical_devices('GPU')}")

from google.colab import drive
drive.mount('/content/drive')

SAVE_DIR = '/content/drive/MyDrive/BridgeLens/model_data'

X = np.load(os.path.join(SAVE_DIR, 'X_sequences.npy'))
y = np.load(os.path.join(SAVE_DIR, 'y_labels.npy'))

with open(os.path.join(SAVE_DIR, 'classes.json')) as f:
    class_list = json.load(f)

print(f"X shape: {X.shape}")   # (868, 30, 225)
print(f"y shape: {y.shape}")
print(f"Classes: {len(class_list)}")
print(f"Sequences per class (avg): {len(X)/len(class_list):.1f}")

le = LabelEncoder()
le.fit(class_list)
y_encoded = le.transform(y)
y_cat     = tf.keras.utils.to_categorical(y_encoded, num_classes=len(class_list))

# Stratified split to ensure every class appears in train and val
X_train, X_val, y_train, y_val = train_test_split(
    X, y_cat,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

X_train, X_test, y_train, y_test = train_test_split(
    X_train, y_train,
    test_size=0.1,
    random_state=42,
    stratify=np.argmax(y_train, axis=1)
)

print(f"Train : {X_train.shape[0]} sequences")
print(f"Val   : {X_val.shape[0]} sequences")
print(f"Test  : {X_test.shape[0]} sequences")

# Class weights to handle imbalance
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_encoded),
    y=y_encoded
)
class_weight_dict = dict(enumerate(class_weights))
print(f"\nClass weight range: {min(class_weights):.2f} – {max(class_weights):.2f}")

def augment_sequence(X, y, noise_factor=0.01, scale_range=0.1):
    """
    Add noise and scale augmentation to increase effective dataset size.
    Critical for small datasets like this one.
    """
    X_aug, y_aug = [], []

    for seq, label in zip(X, y):
        # Original
        X_aug.append(seq)
        y_aug.append(label)

        # Gaussian noise
        noisy = seq + np.random.normal(0, noise_factor, seq.shape)
        X_aug.append(noisy)
        y_aug.append(label)

        # Random scale
        scale = 1.0 + np.random.uniform(-scale_range, scale_range)
        scaled = seq * scale
        X_aug.append(scaled)
        y_aug.append(label)

        # Time shift — roll frames slightly
        shift = np.random.randint(-3, 3)
        shifted = np.roll(seq, shift, axis=0)
        X_aug.append(shifted)
        y_aug.append(label)

    return np.array(X_aug, dtype=np.float32), np.array(y_aug)

X_train_aug, y_train_aug = augment_sequence(X_train, y_train)
print(f"Augmented train size: {X_train_aug.shape[0]} (from {X_train.shape[0]})")

def attention_block(inputs):
    """Self-attention over the time dimension."""
    # inputs shape: (batch, timesteps, features)
    attention = Dense(1, activation='tanh')(inputs)          # (batch, timesteps, 1)
    attention = Flatten()(attention)                          # (batch, timesteps)
    attention = tf.keras.layers.Softmax()(attention)         # normalise
    attention = RepeatVector(inputs.shape[-1])(attention)    # (batch, features, timesteps)
    attention = Permute([2, 1])(attention)                   # (batch, timesteps, features)
    return Multiply()([inputs, attention])                   # weighted input

def build_model(input_shape, num_classes):
    inputs = Input(shape=input_shape)  # (30, 225)

    # Normalise inputs
    x = BatchNormalization()(inputs)

    # First Bidirectional LSTM
    x = Bidirectional(LSTM(
        128,
        return_sequences=True,
        dropout=0.3,
        recurrent_dropout=0.2,
        kernel_regularizer=l2(1e-4)
    ))(x)
    x = BatchNormalization()(x)

    # Attention
    x = attention_block(x)

    # Second Bidirectional LSTM
    x = Bidirectional(LSTM(
        64,
        return_sequences=True,
        dropout=0.3,
        recurrent_dropout=0.2,
        kernel_regularizer=l2(1e-4)
    ))(x)
    x = BatchNormalization()(x)

    # Global average pool over time
    x = GlobalAveragePooling1D()(x)

    # Dense head
    x = Dense(256, activation='relu', kernel_regularizer=l2(1e-4))(x)
    x = Dropout(0.5)(x)
    x = Dense(128, activation='relu', kernel_regularizer=l2(1e-4))(x)
    x = Dropout(0.3)(x)

    outputs = Dense(num_classes, activation='softmax')(x)

    return Model(inputs, outputs)

INPUT_SHAPE = (X_train.shape[1], X_train.shape[2])  # (30, 225)
NUM_CLASSES = len(class_list)

model = build_model(INPUT_SHAPE, NUM_CLASSES)
model.summary()

model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy', tf.keras.metrics.TopKCategoricalAccuracy(k=3, name='top3_acc')]
)

MODEL_DIR = '/content/drive/MyDrive/BridgeLens/models'
os.makedirs(MODEL_DIR, exist_ok=True)

callbacks = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=20,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=8,
        min_lr=1e-6,
        verbose=1
    ),
    ModelCheckpoint(
        filepath=os.path.join(MODEL_DIR, 'best_model.keras'),
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]

history = model.fit(
    X_train_aug, y_train_aug,
    validation_data=(X_val, y_val),
    epochs=150,
    batch_size=32,
    callbacks=callbacks,
    class_weight=class_weight_dict,
    verbose=1
)

# Test set evaluation
test_loss, test_acc, test_top3 = model.evaluate(X_test, y_test, verbose=0)
print(f"\n{'='*40}")
print(f"Test Accuracy    : {test_acc:.4f} ({test_acc*100:.1f}%)")
print(f"Test Top-3 Acc   : {test_top3:.4f} ({test_top3*100:.1f}%)")
print(f"Test Loss        : {test_loss:.4f}")
print(f"{'='*40}")

# Per-class accuracy
y_pred      = model.predict(X_test)
y_pred_cls  = np.argmax(y_pred, axis=1)
y_true_cls  = np.argmax(y_test, axis=1)

print("\nPer-class accuracy:")
for i, cls in enumerate(le.classes_):
    mask = y_true_cls == i
    if mask.sum() > 0:
        acc = (y_pred_cls[mask] == i).mean()
        print(f"  {cls:<15} {acc:.2f}  ({mask.sum()} samples)")

# Training curves
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history.history['accuracy'],     label='Train')
axes[0].plot(history.history['val_accuracy'], label='Val')
axes[0].set_title('Accuracy')
axes[0].set_xlabel('Epoch')
axes[0].legend()

axes[1].plot(history.history['loss'],     label='Train')
axes[1].plot(history.history['val_loss'], label='Val')
axes[1].set_title('Loss')
axes[1].set_xlabel('Epoch')
axes[1].legend()

plt.tight_layout()
plt.savefig(os.path.join(MODEL_DIR, 'training_curves.png'), dpi=150)
plt.show()

from sklearn.model_selection import StratifiedKFold
import numpy as np

# Reload full data
X_full = np.load('/content/drive/MyDrive/BridgeLens/model_data/X_sequences.npy')
y_full = np.load('/content/drive/MyDrive/BridgeLens/model_data/y_labels.npy')
y_full_encoded = le.transform(y_full)

# Simple leave-more-out: evaluate on full dataset
y_full_cat = tf.keras.utils.to_categorical(y_full_encoded, num_classes=len(class_list))
full_loss, full_acc, full_top3 = model.evaluate(X_full, y_full_cat, verbose=0)

print(f"Full dataset accuracy : {full_acc*100:.1f}%")
print(f"Full dataset top-3    : {full_top3*100:.1f}%")

# Per class with full data — more reliable counts
y_pred_full     = model.predict(X_full)
y_pred_cls_full = np.argmax(y_pred_full, axis=1)

print(f"\n{'Class':<15} {'Acc':>6} {'Samples':>8}")
print("-" * 32)
for i, cls in enumerate(le.classes_):
    mask    = y_full_encoded == i
    n       = mask.sum()
    acc     = (y_pred_cls_full[mask] == i).mean()
    status  = "⚠️ " if acc < 0.5 else "✅"
    print(f"{status} {cls:<13} {acc:>6.2f} {n:>8}")



"""# **INFERENCE PIPELINE Section**"""

!pip install mediapipe

import numpy as np
import tensorflow as tf
import mediapipe as mp
import json
import pickle
import cv2
from collections import deque, Counter
from google.colab import files
from IPython.display import display, Image as IPImage
import matplotlib.pyplot as plt
import io

# Mount drive
from google.colab import drive
drive.mount('/content/drive')

MODEL_DIR      = '/content/drive/MyDrive/BridgeLens/models'
MODEL_DATA_DIR = '/content/drive/MyDrive/BridgeLens/model_data'

# ── Verify files exist before loading ─────────────────────────
import os
for path in [
    f'{MODEL_DIR}/best_model.keras',
    f'{MODEL_DATA_DIR}/classes.json',
    f'{MODEL_DATA_DIR}/label_encoder.pkl',
]:
    exists = "✅" if os.path.exists(path) else "❌ MISSING"
    print(f"{exists} {path}")

# Recreate and save label_encoder.pkl from existing data
import pickle
from sklearn.preprocessing import LabelEncoder
import json

with open(f'{MODEL_DATA_DIR}/classes.json') as f:
    class_list = json.load(f)

le = LabelEncoder()
le.fit(class_list)

with open(f'{MODEL_DATA_DIR}/label_encoder.pkl', 'wb') as f:
    pickle.dump(le, f)

print(f"✅ label_encoder.pkl saved with {len(le.classes_)} classes")
print(f"Classes: {list(le.classes_)}")

import pickle, json

model = tf.keras.models.load_model(f'{MODEL_DIR}/best_model.keras')
print("✅ Model loaded")

with open(f'{MODEL_DATA_DIR}/classes.json') as f:
    class_list = json.load(f)
print(f"✅ Classes loaded — {len(class_list)} classes")

with open(f'{MODEL_DATA_DIR}/label_encoder.pkl', 'rb') as f:
    le = pickle.load(f)

print(f"✅ Model encoder loaded — {len(class_list)} classes")

!wget -q https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/latest/pose_landmarker_full.task -O /content/pose_landmarker.task
!wget -q https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/latest/hand_landmarker.task -O /content/hand_landmarker.task

BaseOptions       = mp.tasks.BaseOptions
VisionRunningMode = mp.tasks.vision.RunningMode

pose_options = mp.tasks.vision.PoseLandmarkerOptions(
    base_options=BaseOptions(model_asset_path='/content/pose_landmarker.task'),
    running_mode=VisionRunningMode.IMAGE,
    num_poses=1,
    min_pose_detection_confidence=0.4,
    min_pose_presence_confidence=0.4,
    min_tracking_confidence=0.4,
    output_segmentation_masks=False
)

hand_options = mp.tasks.vision.HandLandmarkerOptions(
    base_options=BaseOptions(model_asset_path='/content/hand_landmarker.task'),
    running_mode=VisionRunningMode.IMAGE,
    num_hands=2,
    min_hand_detection_confidence=0.4,
    min_hand_presence_confidence=0.4,
    min_tracking_confidence=0.4
)

print("✅ MediaPipe ready")

SEQUENCE_LENGTH   = 30
LANDMARK_SIZE     = 225
CONFIDENCE_THRESH = 0.40

def extract_landmarks(frame_rgb, pose_det, hand_det):
    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame_rgb)
    row = []

    pose_result = pose_det.detect(mp_image)
    if pose_result.pose_landmarks:
        for lm in pose_result.pose_landmarks[0]:
            row.extend([lm.x, lm.y, lm.z])
    else:
        row.extend([0.0] * 33 * 3)

    hand_result = hand_det.detect(mp_image)
    left  = [0.0] * 21 * 3
    right = [0.0] * 21 * 3

    if hand_result.hand_landmarks:
        for i, hand_lms in enumerate(hand_result.hand_landmarks):
            handedness = hand_result.handedness[i][0].category_name
            coords = [c for lm in hand_lms for c in [lm.x, lm.y, lm.z]]
            if handedness == 'Left':
                left = coords
            else:
                right = coords

    row.extend(left)
    row.extend(right)
    return row

def predict_sequence(sequence):
    arr   = np.array(sequence, dtype=np.float32)
    arr   = np.expand_dims(arr, axis=0)
    probs = model.predict(arr, verbose=0)[0]
    top3  = np.argsort(probs)[::-1][:3]
    return [
        {'label': le.inverse_transform([i])[0], 'confidence': float(probs[i])}
        for i in top3
    ]

def draw_results(frame, results, title="Prediction"):
    """Draw prediction results on frame and return as matplotlib figure."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Left — annotated frame
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) if len(frame.shape) == 3 else frame
    axes[0].imshow(frame_rgb)
    axes[0].set_title(title, fontsize=14, fontweight='bold')
    axes[0].axis('off')

    # Right — confidence bar chart
    labels = [r['label'] for r in results]
    confs  = [r['confidence'] for r in results]
    colors = ['#00C851', '#FF8800', '#0099CC']

    bars = axes[1].barh(labels[::-1], confs[::-1], color=colors[::-1])
    axes[1].set_xlim(0, 1)
    axes[1].set_xlabel('Confidence', fontsize=12)
    axes[1].set_title('Top-3 Predictions', fontsize=14, fontweight='bold')

    for bar, conf in zip(bars, confs[::-1]):
        axes[1].text(
            bar.get_width() + 0.01,
            bar.get_y() + bar.get_height() / 2,
            f'{conf*100:.1f}%',
            va='center', fontsize=12, fontweight='bold'
        )

    # Big label overlay
    top_label = results[0]['label']
    top_conf  = results[0]['confidence']
    color     = 'green' if top_conf > CONFIDENCE_THRESH else 'orange'
    axes[0].text(
        0.5, 0.05, f"{top_label}  ({top_conf*100:.0f}%)",
        transform=axes[0].transAxes,
        fontsize=22, fontweight='bold', color=color,
        ha='center', va='bottom',
        bbox=dict(boxstyle='round,pad=0.3', facecolor='black', alpha=0.7)
    )

    plt.tight_layout()
    return fig

print("✅ Functions ready")

# Upload any image of someone signing
uploaded = files.upload()
filename = list(uploaded.keys())[0]

frame = cv2.imdecode(np.frombuffer(uploaded[filename], np.uint8), cv2.IMREAD_COLOR)
rgb   = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

with mp.tasks.vision.PoseLandmarker.create_from_options(pose_options) as pose_det, \
     mp.tasks.vision.HandLandmarker.create_from_options(hand_options) as hand_det:

    # Single image — repeat the frame to fill the sequence
    # (simulates a held sign position)
    landmarks = extract_landmarks(rgb, pose_det, hand_det)
    hand_detected = any(v != 0.0 for v in landmarks[33*3:])

    if not hand_detected:
        print("⚠️ No hands detected in image. Try a clearer image.")
    else:
        sequence = [landmarks] * SEQUENCE_LENGTH  # repeat single frame
        results  = predict_sequence(sequence)

        print("\n" + "="*40)
        print("PREDICTIONS")
        print("="*40)
        for i, r in enumerate(results):
            rank = ["🥇", "🥈", "🥉"][i]
            print(f"{rank} {r['label']:<15} {r['confidence']*100:.1f}%")

        fig = draw_results(frame, results, title=filename)
        plt.show()

```javascript
const SIGN_VIDEOS = {
  "AFRAID":   "https://res.cloudinary.com/duf8tknie/video/upload/AFRAID_mkyoxe.mp4",
  "ANGRY":    "https://res.cloudinary.com/duf8tknie/video/upload/ANGRY_nnacu2.mp4",
  "BAD":      "https://res.cloudinary.com/duf8tknie/video/upload/BAD_wyzeec.mp4",
  "BANK":     "https://res.cloudinary.com/duf8tknie/video/upload/BANK_ytupym.mp4",
  "BLOOD":    "https://res.cloudinary.com/duf8tknie/video/upload/BLOOD_ab20zn.mp4",
  "BORROW":   "https://res.cloudinary.com/duf8tknie/video/upload/BORROW_or8cya.mp4",
  "BREATHE":  "https://res.cloudinary.com/duf8tknie/video/upload/BREATHE_xg8pui.mp4",
  "BUY":      "https://res.cloudinary.com/duf8tknie/video/upload/BUY_zfbssq.mp4",
  "CALM":     "https://res.cloudinary.com/duf8tknie/video/upload/CALM_wszok2.mp4",
  "COME":     "https://res.cloudinary.com/duf8tknie/video/upload/COME_vtzov8.mp4",
  "COST":     "https://res.cloudinary.com/duf8tknie/video/upload/COST_y7wrqy.mp4",
  "DIZZY":    "https://res.cloudinary.com/duf8tknie/video/upload/DIZZY_zqhqxj.mp4",
  "DOCTOR":   "https://res.cloudinary.com/duf8tknie/video/upload/DOCTOR_ibeb4z.mp4",
  "FINE":     "https://res.cloudinary.com/duf8tknie/video/upload/FINE_nnquvh.mp4",
  "FREE":     "https://res.cloudinary.com/duf8tknie/video/upload/FREE_xvmg2m.mp4",
  "GIVE":     "https://res.cloudinary.com/duf8tknie/video/upload/GIVE_mhu4xf.mp4",
  "GO":       "https://res.cloudinary.com/duf8tknie/video/upload/GO_fm8d03.mp4",
  "GOOD":     "https://res.cloudinary.com/duf8tknie/video/upload/GOOD_x0njt3.mp4",
  "GOODBYE":  "https://res.cloudinary.com/duf8tknie/video/upload/GOODBYE_pb2gvt.mp4",
  "HAPPY":    "https://res.cloudinary.com/duf8tknie/video/upload/HAPPY_cx3soj.mp4",
  "HATE":     "https://res.cloudinary.com/duf8tknie/video/upload/HATE_w5rk8h.mp4",
  "HEADACHE": "https://res.cloudinary.com/duf8tknie/video/upload/HEADACHE_bcerif.mp4",
  "HEART":    "https://res.cloudinary.com/duf8tknie/video/upload/HEART_ixhulk.mp4",
  "HELLO":    "https://res.cloudinary.com/duf8tknie/video/upload/HELLO_skstln.mp4",
  "HELP":     "https://res.cloudinary.com/duf8tknie/video/upload/HELP_wlwqhz.mp4",
  "HOSPITAL": "https://res.cloudinary.com/duf8tknie/video/upload/HOSPITALhblhkc.mp4",
  "HOW":      "https://res.cloudinary.com/duf8tknie/video/upload/HOW_aai6v2.mp4",
  "HUNGRY":   "https://res.cloudinary.com/duf8tknie/video/upload/HUNGRY_jh7769.mp4",
  "LIKE":     "https://res.cloudinary.com/duf8tknie/video/upload/LIKE_ytcy4s.mp4",
  "LOVE":     "https://res.cloudinary.com/duf8tknie/video/upload/LOVE_xtbon2.mp4",
  "MEDICINE": "https://res.cloudinary.com/duf8tknie/video/upload/MEDICINE_f4fmir.mp4",
  "MEET":     "https://res.cloudinary.com/duf8tknie/video/upload/MEET_ujnj8t.mp4",
  "MONEY":    "https://res.cloudinary.com/duf8tknie/video/upload/MONEY_vunjs5.mp4",
  "MORNING":  "https://res.cloudinary.com/duf8tknie/video/upload/MORNING_tkqyin.mp4",
  "NAME":     "https://res.cloudinary.com/duf8tknie/video/upload/NAME_krht1z.mp4",
  "NIGHT":    "https://res.cloudinary.com/duf8tknie/video/upload/NIGHT_wqjkp7.mp4",
  "NO":       "https://res.cloudinary.com/duf8tknie/video/upload/NO_y5taja.mp4",
  "PAIN":     "https://res.cloudinary.com/duf8tknie/video/upload/PAIN_iqzxl0.mp4",
  "PAY":      "https://res.cloudinary.com/duf8tknie/video/upload/PAY_bfp4uz.mp4",
  "PLEASE":   "https://res.cloudinary.com/duf8tknie/video/upload/PLEASE_vuscnr.mp4",
  "PREGNANT": "https://res.cloudinary.com/duf8tknie/video/upload/PREGNANT_yaibbd.mp4",
  "SAD":      "https://res.cloudinary.com/duf8tknie/video/upload/SAD_ms5ydx.mp4",
  "SAVE":     "https://res.cloudinary.com/duf8tknie/video/upload/SAVE_ysonpb.mp4",
  "SCARED":   "https://res.cloudinary.com/duf8tknie/video/upload/SCARED_a7oofc.mp4",
  "SELL":     "https://res.cloudinary.com/duf8tknie/video/upload/SELL_yjzyu2.mp4",
  "SICK":     "https://res.cloudinary.com/duf8tknie/video/upload/SICK_teqogk.mp4",
  "SORRY":    "https://res.cloudinary.com/duf8tknie/video/upload/SORRY_ay4lak.mp4",
  "STOP":     "https://res.cloudinary.com/duf8tknie/video/upload/STOP_eeg16v.mp4",
  "TIRED":    "https://res.cloudinary.com/duf8tknie/video/upload/TIRED_xavvfm.mp4",
  "WAIT":     "https://res.cloudinary.com/duf8tknie/video/upload/WAIT_w5072p.mp4",
  "WANT":     "https://res.cloudinary.com/duf8tknie/video/upload/WANT_dukqjv.mp4",
  "WATER":    "https://res.cloudinary.com/duf8tknie/video/upload/WATER_mmwoec.mp4",
  "WELCOME":  "https://res.cloudinary.com/duf8tknie/video/upload/WELCOME_kpttck.mp4",
  "WHAT":     "https://res.cloudinary.com/duf8tknie/video/upload/WHAT_tjcbba.mp4",
  "WHERE":    "https://res.cloudinary.com/duf8tknie/video/upload/WHERE_iuc1pd.mp4",
  "WHO":      "https://res.cloudinary.com/duf8tknie/video/upload/WHO_fkf9ef.mp4",
  "YES":      "https://res.cloudinary.com/duf8tknie/video/upload/YES_wp9ece.mp4"
};

!curl -o models/pose_landmarker.task https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/latest/pose_landmarker_full.task

!wget -q https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/latest/pose_landmarker_full.task -O /content/pose_landmarker.task
!wget -q https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/latest/hand_landmarker.task -O /content/hand_landmarker.task



# Upload an mp4 of someone signing — this is the real test
uploaded = files.upload()
filename = list(uploaded.keys())[0]

with open(f'/content/{filename}', 'wb') as f:
    f.write(uploaded[filename])

print(f"Processing video: {filename}")

with mp.tasks.vision.PoseLandmarker.create_from_options(pose_options) as pose_det, \
     mp.tasks.vision.HandLandmarker.create_from_options(hand_options) as hand_det:

    cap          = cv2.VideoCapture(f'/content/{filename}')
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    step         = max(1, total_frames // SEQUENCE_LENGTH)

    sequence  = []
    frame_idx = 0
    frames_for_display = []

    while cap.isOpened() and len(sequence) < SEQUENCE_LENGTH:
        ret, frame = cap.read()
        if not ret:
            break
        if frame_idx % step == 0:
            rgb       = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            landmarks = extract_landmarks(rgb, pose_det, hand_det)
            sequence.append(landmarks)
            if len(frames_for_display) < 6:
                frames_for_display.append(rgb.copy())
        frame_idx += 1
    cap.release()

    # Pad if short
    while len(sequence) < SEQUENCE_LENGTH:
        sequence.append([0.0] * LANDMARK_SIZE)

    print(f"  Extracted {len(sequence)} frames from {total_frames} total")

    hand_detected = any(
        any(v != 0.0 for v in frame[33*3:])
        for frame in sequence
    )

    if not hand_detected:
        print("⚠️ No hands detected across the video.")
    else:
        results = predict_sequence(sequence)

        print("\n" + "="*40)
        print("PREDICTIONS")
        print("="*40)
        for i, r in enumerate(results):
            rank = ["🥇", "🥈", "🥉"][i]
            print(f"{rank} {r['label']:<15} {r['confidence']*100:.1f}%")

        # Show sampled frames
        fig, axes = plt.subplots(2, 3, figsize=(15, 8))
        fig.suptitle(
            f"Top prediction: {results[0]['label']} ({results[0]['confidence']*100:.0f}%)",
            fontsize=16, fontweight='bold', color='green'
        )
        for i, ax in enumerate(axes.flat):
            if i < len(frames_for_display):
                ax.imshow(frames_for_display[i])
                ax.set_title(f"Frame {i+1}", fontsize=10)
            ax.axis('off')
        plt.tight_layout()
        plt.show()

        # Bar chart
        fig2 = draw_results(frames_for_display[0], results, title="Video Prediction")
        plt.show()

# This simulates the real sliding window behaviour on a video
uploaded = files.upload()
filename = list(uploaded.keys())[0]

with open(f'/content/{filename}', 'wb') as f:
    f.write(uploaded[filename])

STRIDE = 5  # predict every 5 new frames

buffer             = deque(maxlen=SEQUENCE_LENGTH)
prediction_history = deque(maxlen=5)
all_predictions    = []  # track predictions over time

with mp.tasks.vision.PoseLandmarker.create_from_options(pose_options) as pose_det, \
     mp.tasks.vision.HandLandmarker.create_from_options(hand_options) as hand_det:

    cap       = cv2.VideoCapture(f'/content/{filename}')
    frame_idx = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        rgb           = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        landmarks     = extract_landmarks(rgb, pose_det, hand_det)
        hand_detected = any(v != 0.0 for v in landmarks[33*3:])

        if hand_detected:
            buffer.append(landmarks)

        if len(buffer) == SEQUENCE_LENGTH and frame_idx % STRIDE == 0:
            results = predict_sequence(list(buffer))
            top1    = results[0]
            prediction_history.append(top1['label'])

            # Majority vote
            counts         = Counter(prediction_history)
            stable_label   = counts.most_common(1)[0][0]
            stable_count   = counts.most_common(1)[0][1]

            all_predictions.append({
                'frame':      frame_idx,
                'top1':       top1['label'],
                'confidence': top1['confidence'],
                'stable':     stable_label,
                'agreed':     stable_count >= 3
            })

        frame_idx += 1
    cap.release()

# ── Results summary ───────────────────────────────────────────
print(f"\nProcessed {frame_idx} frames, made {len(all_predictions)} predictions\n")
print(f"{'Frame':<8} {'Raw Pred':<15} {'Conf':<8} {'Stable':<15} {'Agreed?'}")
print("-" * 55)
for p in all_predictions:
    agreed = "✅" if p['agreed'] else "  "
    print(f"{p['frame']:<8} {p['top1']:<15} {p['confidence']*100:.0f}%{'':<4} {p['stable']:<15} {agreed}")

# Final stable prediction
agreed_preds = [p['stable'] for p in all_predictions if p['agreed']]
if agreed_preds:
    final = Counter(agreed_preds).most_common(1)[0][0]
    print(f"\n🎯 Final stable prediction: {final}")
else:
    if all_predictions:
        final = Counter([p['top1'] for p in all_predictions]).most_common(1)[0][0]
        print(f"\n🎯 Most common prediction: {final}")
    else:
        print("\n⚠️ No predictions made — check if hands are visible in video")

